[tool.poetry]
name = "streamlit-manim"
version = "0.1.0"
description = ""
authors = ["darthVarada <fafapelegia@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
